"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 06:53:14.469994
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('at', sa.String(length=40), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_at'), ['at'], unique=False)

    op.create_table('episodes',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sources',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.String(length=40), nullable=False),
    sa.Column('accessed_date', sa.String(length=40), nullable=False),
    sa.Column('geo_coverage', sa.String(length=200), nullable=False),
    sa.Column('time_coverage', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('reliability', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('episode_id', sa.String(length=80), nullable=True),
    sa.Column('agent', sa.String(length=120), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('settlement', sa.String(length=20), nullable=False),
    sa.Column('starting_class', sa.String(length=20), nullable=False),
    sa.Column('family', sa.JSON(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=False),
    sa.Column('controls', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_episode_id'), ['episode_id'], unique=True)

    op.create_table('economic_years',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('spouse_income', sa.Float(), nullable=False),
    sa.Column('housing', sa.Float(), nullable=False),
    sa.Column('food', sa.Float(), nullable=False),
    sa.Column('education', sa.Float(), nullable=False),
    sa.Column('healthcare', sa.Float(), nullable=False),
    sa.Column('transport', sa.Float(), nullable=False),
    sa.Column('family_support', sa.Float(), nullable=False),
    sa.Column('debt', sa.Float(), nullable=False),
    sa.Column('savings', sa.Float(), nullable=False),
    sa.Column('investments', sa.Float(), nullable=False),
    sa.Column('assets', sa.Float(), nullable=False),
    sa.Column('liabilities', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_index', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('economic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_economic_years_episode_id'), ['episode_id'], unique=False)

    op.create_table('facts',
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('fact_type', sa.String(length=12), nullable=False),
    sa.Column('derived_from', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_episode_id'), ['episode_id'], unique=False)

    op.create_table('research_tasks',
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('period', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=120), nullable=False),
    sa.Column('fact_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_tasks_episode_id'), ['episode_id'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('controls', sa.JSON(), nullable=False),
    sa.Column('decision_points', sa.JSON(), nullable=False),
    sa.Column('is_prototype', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_episode_id'), ['episode_id'], unique=False)

    op.create_table('story_chapters',
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('timeline_event_ids', sa.JSON(), nullable=False),
    sa.Column('fact_ids', sa.JSON(), nullable=False),
    sa.Column('assumption_ids', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emotional_arc', sa.Text(), nullable=False),
    sa.Column('unresolved', sa.Text(), nullable=False),
    sa.Column('engagement', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_chapters_episode_id'), ['episode_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('financial_effect', sa.String(length=300), nullable=False),
    sa.Column('emotions', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('fact_ids', sa.JSON(), nullable=False),
    sa.Column('simulation_reason', sa.Text(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_episode_id'), ['episode_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_episode_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('story_chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_chapters_episode_id'))

    op.drop_table('story_chapters')
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_episode_id'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('research_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_tasks_episode_id'))

    op.drop_table('research_tasks')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_episode_id'))

    op.drop_table('facts')
    with op.batch_alter_table('economic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_economic_years_episode_id'))

    op.drop_table('economic_years')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_episode_id'))

    op.drop_table('characters')
    op.drop_table('agent_runs')
    op.drop_table('sources')
    op.drop_table('meta')
    op.drop_table('episodes')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_at'))

    op.drop_table('activity')
    # ### end Alembic commands ###
