"""truth and economic engine

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 17:35:55.780112
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_observations',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=False),
    sa.Column('indicator_code', sa.String(length=80), nullable=False),
    sa.Column('indicator_name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('country_name', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('source_organization', sa.Text(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('provider_last_updated', sa.String(length=40), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_observations_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_observations_indicator_code'), ['indicator_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_observations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_observations_year'), ['year'], unique=False)

    op.create_table('provider_syncs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_syncs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_syncs_provider'), ['provider'], unique=False)

    op.create_table('episode_dataset_snapshots',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episode_dataset_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_dataset_snapshots_episode_id'), ['episode_id'], unique=False)

    op.create_table('observation_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.String(length=160), nullable=False),
    sa.Column('old_value', sa.String(length=60), nullable=False),
    sa.Column('new_value', sa.String(length=60), nullable=False),
    sa.Column('old_retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('new_retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('old_provider_last_updated', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['external_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_revisions_observation_id'), ['observation_id'], unique=False)

    op.create_table('wage_observations',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('experience_level', sa.String(length=80), nullable=False),
    sa.Column('education', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=40), nullable=False),
    sa.Column('sector', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('basis', sa.String(length=10), nullable=False),
    sa.Column('statistic', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source_population', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('retrieved_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derived_calculations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=True),
    sa.Column('output_fact_id', sa.String(length=80), nullable=True),
    sa.Column('calculation_type', sa.String(length=40), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('formula_version', sa.String(length=40), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_fact_id'], ['facts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('derived_calculations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_derived_calculations_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_derived_calculations_output_fact_id'), ['output_fact_id'], unique=False)

    op.create_table('calculation_inputs',
    sa.Column('calculation_id', sa.String(length=80), nullable=False),
    sa.Column('fact_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['derived_calculations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('calculation_id', 'fact_id', 'role')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('external_observation_id', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('dataset', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('indicator_code', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('is_prototype', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_foreign_key('fk_facts_external_observation', 'external_observations', ['external_observation_id'], ['id'], ondelete='SET NULL')

    # Phase 2 data: every fact in a mock episode is PROTOTYPE data, never verified history.
    op.execute("UPDATE facts SET is_prototype = 1 WHERE episode_id IN (SELECT id FROM episodes WHERE is_mock = 1)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_facts_external_observation', type_='foreignkey')
        batch_op.drop_column('is_prototype')
        batch_op.drop_column('indicator_code')
        batch_op.drop_column('dataset')
        batch_op.drop_column('provider')
        batch_op.drop_column('external_observation_id')
        batch_op.drop_column('currency')

    op.drop_table('calculation_inputs')
    with op.batch_alter_table('derived_calculations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_derived_calculations_output_fact_id'))
        batch_op.drop_index(batch_op.f('ix_derived_calculations_episode_id'))

    op.drop_table('derived_calculations')
    op.drop_table('wage_observations')
    with op.batch_alter_table('observation_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_revisions_observation_id'))

    op.drop_table('observation_revisions')
    with op.batch_alter_table('episode_dataset_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_dataset_snapshots_episode_id'))

    op.drop_table('episode_dataset_snapshots')
    with op.batch_alter_table('provider_syncs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_syncs_provider'))

    op.drop_table('provider_syncs')
    with op.batch_alter_table('external_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_observations_year'))
        batch_op.drop_index(batch_op.f('ix_external_observations_provider'))
        batch_op.drop_index(batch_op.f('ix_external_observations_indicator_code'))
        batch_op.drop_index(batch_op.f('ix_external_observations_country_code'))

    op.drop_table('external_observations')
    # ### end Alembic commands ###
