"""labor evidence and snapshots

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 19:44:56.869229
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wage_distributions',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('pay_period', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('source_organization', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wage_distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wage_distributions_country'), ['country'], unique=False)

    op.create_table('character_economic_profiles',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('life_stage', sa.String(length=40), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_economic_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_economic_profiles_episode_id'), ['episode_id'], unique=False)

    op.create_table('evidence_gaps',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('gap_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('research_task_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_gaps_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_gaps_gap_key'), ['gap_key'], unique=False)

    op.create_table('household_units',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('household_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_units_episode_id'), ['episode_id'], unique=False)

    op.create_table('wage_distribution_bins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distribution_id', sa.String(length=200), nullable=False),
    sa.Column('lower_bound', sa.String(length=40), nullable=True),
    sa.Column('upper_bound', sa.String(length=40), nullable=True),
    sa.Column('open_lower', sa.Boolean(), nullable=False),
    sa.Column('open_upper', sa.Boolean(), nullable=False),
    sa.Column('count', sa.String(length=40), nullable=True),
    sa.Column('share', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('external_observation_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['distribution_id'], ['wage_distributions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wage_distribution_bins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wage_distribution_bins_distribution_id'), ['distribution_id'], unique=False)

    op.create_table('candidate_reviews',
    sa.Column('profile_id', sa.String(length=80), nullable=False),
    sa.Column('wage_observation_id', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['character_economic_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'wage_observation_id')
    )
    op.create_table('economic_baselines',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('profile_id', sa.String(length=80), nullable=True),
    sa.Column('life_stage', sa.String(length=40), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.String(length=40), nullable=False),
    sa.Column('occupation', sa.String(length=200), nullable=False),
    sa.Column('baseline_type', sa.String(length=16), nullable=False),
    sa.Column('estimate_kind', sa.String(length=12), nullable=False),
    sa.Column('low', sa.String(length=60), nullable=True),
    sa.Column('high', sa.String(length=60), nullable=True),
    sa.Column('point', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('pay_period', sa.String(length=10), nullable=False),
    sa.Column('gross_or_net', sa.String(length=10), nullable=False),
    sa.Column('annualization', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('confidence_reasons', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('source_fact_ids', sa.JSON(), nullable=False),
    sa.Column('derived_calculation_ids', sa.JSON(), nullable=False),
    sa.Column('assumption_fact_id', sa.String(length=80), nullable=True),
    sa.Column('user_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['character_economic_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('economic_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_economic_baselines_episode_id'), ['episode_id'], unique=False)

    op.create_table('income_streams',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('household_id', sa.String(length=80), nullable=False),
    sa.Column('member_id', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('low', sa.String(length=60), nullable=True),
    sa.Column('high', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('pay_period', sa.String(length=10), nullable=True),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('baseline_id', sa.String(length=80), nullable=True),
    sa.Column('fact_id', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_streams_household_id'), ['household_id'], unique=False)

    op.create_table('snapshot_baselines',
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('economic_baseline_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['episode_dataset_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'economic_baseline_id')
    )
    op.create_table('snapshot_facts',
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('fact_id', sa.String(length=80), nullable=False),
    sa.Column('fact_updated_at', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['episode_dataset_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'fact_id')
    )
    op.create_table('snapshot_observations',
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('external_observation_id', sa.String(length=160), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['episode_dataset_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'external_observation_id')
    )
    with op.batch_alter_table('episode_dataset_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('parent_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('finalized_at', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))

    with op.batch_alter_table('wage_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_observation_id', sa.String(length=160), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=8), nullable=False))
        batch_op.add_column(sa.Column('frequency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('statistic_type', sa.String(length=14), nullable=False))
        batch_op.add_column(sa.Column('pay_period', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('nominal_or_real', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('gross_or_net', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('employee_scope', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('occupation_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('occupation_label', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('occupation_classification', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('industry_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('industry_label', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('industry_classification', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('education_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('education_label', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('education_classification', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('age_group', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('rural_urban', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('citizenship', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('migrant_status', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('formal_informal', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('full_part_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('survey_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.String(length=40), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_wage_observations_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_wage_observations_external_observation_id'), ['external_observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wage_observations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_wage_observations_year'), ['year'], unique=False)
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'external_observations', ['external_observation_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('source_id')
        batch_op.drop_column('basis')
        batch_op.drop_column('retrieved_at')
        batch_op.drop_column('dataset')
        batch_op.drop_column('country_code')
        batch_op.drop_column('occupation')
        batch_op.drop_column('education')
        batch_op.drop_column('industry')
        batch_op.drop_column('gender')
        batch_op.drop_column('sector')
        batch_op.drop_column('experience_level')
        batch_op.drop_column('statistic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statistic', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('experience_level', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('sector', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('industry', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('education', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('country_code', sa.VARCHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('dataset', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('retrieved_at', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('basis', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('source_id', sa.VARCHAR(length=80), nullable=True))
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sources', ['source_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_wage_observations_year'))
        batch_op.drop_index(batch_op.f('ix_wage_observations_provider'))
        batch_op.drop_index(batch_op.f('ix_wage_observations_external_observation_id'))
        batch_op.drop_index(batch_op.f('ix_wage_observations_country'))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('confidence')
        batch_op.drop_column('survey_name')
        batch_op.drop_column('full_part_time')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('formal_informal')
        batch_op.drop_column('migrant_status')
        batch_op.drop_column('citizenship')
        batch_op.drop_column('rural_urban')
        batch_op.drop_column('age_group')
        batch_op.drop_column('sex')
        batch_op.drop_column('education_classification')
        batch_op.drop_column('education_label')
        batch_op.drop_column('education_code')
        batch_op.drop_column('industry_classification')
        batch_op.drop_column('industry_label')
        batch_op.drop_column('industry_code')
        batch_op.drop_column('occupation_classification')
        batch_op.drop_column('occupation_label')
        batch_op.drop_column('occupation_code')
        batch_op.drop_column('employee_scope')
        batch_op.drop_column('gross_or_net')
        batch_op.drop_column('nominal_or_real')
        batch_op.drop_column('pay_period')
        batch_op.drop_column('statistic_type')
        batch_op.drop_column('frequency')
        batch_op.drop_column('country')
        batch_op.drop_column('external_observation_id')

    with op.batch_alter_table('episode_dataset_snapshots', schema=None) as batch_op:
        batch_op.drop_column('content_hash')
        batch_op.drop_column('finalized_at')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('version')
        batch_op.drop_column('notes')
        batch_op.drop_column('status')

    op.drop_table('snapshot_observations')
    op.drop_table('snapshot_facts')
    op.drop_table('snapshot_baselines')
    with op.batch_alter_table('income_streams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_streams_household_id'))

    op.drop_table('income_streams')
    with op.batch_alter_table('economic_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_economic_baselines_episode_id'))

    op.drop_table('economic_baselines')
    op.drop_table('candidate_reviews')
    with op.batch_alter_table('wage_distribution_bins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wage_distribution_bins_distribution_id'))

    op.drop_table('wage_distribution_bins')
    with op.batch_alter_table('household_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_units_episode_id'))

    op.drop_table('household_units')
    with op.batch_alter_table('evidence_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_gaps_gap_key'))
        batch_op.drop_index(batch_op.f('ix_evidence_gaps_episode_id'))

    op.drop_table('evidence_gaps')
    with op.batch_alter_table('character_economic_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_economic_profiles_episode_id'))

    op.drop_table('character_economic_profiles')
    with op.batch_alter_table('wage_distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wage_distributions_country'))

    op.drop_table('wage_distributions')
    # ### end Alembic commands ###
