"""labor evidence and snapshots

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 19:44:56.869229
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wage_distributions',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('pay_period', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('source_organization', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wage_distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wage_distributions_country'), ['country'], unique=False)

    op.create_table('character_economic_profiles',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('life_stage', sa.String(length=40), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_economic_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_economic_profiles_episode_id'), ['episode_id'], unique=False)

    op.create_table('evidence_gaps',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('gap_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('research_task_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_gaps_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_gaps_gap_key'), ['gap_key'], unique=False)

    op.create_table('household_units',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('household_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_units_episode_id'), ['episode_id'], unique=False)

    op.create_table('wage_distribution_bins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distribution_id', sa.String(length=200), nullable=False),
    sa.Column('lower_bound', sa.String(length=40), nullable=True),
    sa.Column('upper_bound', sa.String(length=40), nullable=True),
    sa.Column('open_lower', sa.Boolean(), nullable=False),
    sa.Column('open_upper', sa.Boolean(), nullable=False),
    sa.Column('count', sa.String(length=40), nullable=True),
    sa.Column('share', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('external_observation_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['distribution_id'], ['wage_distributions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wage_distribution_bins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wage_distribution_bins_distribution_id'), ['distribution_id'], unique=False)

    op.create_table('candidate_reviews',
    sa.Column('profile_id', sa.String(length=80), nullable=False),
    sa.Column('wage_observation_id', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['character_economic_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'wage_observation_id')
    )
    op.create_table('economic_baselines',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('profile_id', sa.String(length=80), nullable=True),
    sa.Column('life_stage', sa.String(length=40), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.String(length=40), nullable=False),
    sa.Column('occupation', sa.String(length=200), nullable=False),
    sa.Column('baseline_type', sa.String(length=16), nullable=False),
    sa.Column('estimate_kind', sa.String(length=12), nullable=False),
    sa.Column('low', sa.String(length=60), nullable=True),
    sa.Column('high', sa.String(length=60), nullable=True),
    sa.Column('point', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('pay_period', sa.String(length=10), nullable=False),
    sa.Column('gross_or_net', sa.String(length=10), nullable=False),
    sa.Column('annualization', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('confidence_reasons', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('source_fact_ids', sa.JSON(), nullable=False),
    sa.Column('derived_calculation_ids', sa.JSON(), nullable=False),
    sa.Column('assumption_fact_id', sa.String(length=80), nullable=True),
    sa.Column('user_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['character_economic_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('economic_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_economic_baselines_episode_id'), ['episode_id'], unique=False)

    op.create_table('income_streams',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('household_id', sa.String(length=80), nullable=False),
    sa.Column('member_id', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('low', sa.String(length=60), nullable=True),
    sa.Column('high', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('pay_period', sa.String(length=10), nullable=True),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('baseline_id', sa.String(length=80), nullable=True),
    sa.Column('fact_id', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_streams_household_id'), ['household_id'], unique=False)

    op.create_table('snapshot_baselines',
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('economic_baseline_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['episode_dataset_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'economic_baseline_id')
    )
    op.create_table('snapshot_facts',
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('fact_id', sa.String(length=80), nullable=False),
    sa.Column('fact_updated_at', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['episode_dataset_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'fact_id')
    )
    op.create_table('snapshot_observations',
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('external_observation_id', sa.String(length=160), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['episode_dataset_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'external_observation_id')
    )
    with op.batch_alter_table('episode_dataset_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('parent_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('finalized_at', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))

    # Phase 3 left an empty placeholder wage table (nothing ever wrote to it); replace it.
    bind = op.get_bind()
    n = bind.execute(sa.text("SELECT COUNT(*) FROM wage_observations")).scalar()
    if n:
        raise RuntimeError("wage_observations unexpectedly contains rows; refusing to drop it")
    op.drop_table('wage_observations')
    op.create_table('wage_observations',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('external_observation_id', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('statistic_type', sa.String(length=14), nullable=False),
    sa.Column('pay_period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('nominal_or_real', sa.String(length=80), nullable=False),
    sa.Column('gross_or_net', sa.String(length=10), nullable=False),
    sa.Column('employee_scope', sa.String(length=120), nullable=True),
    sa.Column('occupation_code', sa.String(length=40), nullable=True),
    sa.Column('occupation_label', sa.String(length=200), nullable=True),
    sa.Column('occupation_classification', sa.String(length=40), nullable=True),
    sa.Column('industry_code', sa.String(length=40), nullable=True),
    sa.Column('industry_label', sa.String(length=200), nullable=True),
    sa.Column('industry_classification', sa.String(length=40), nullable=True),
    sa.Column('education_code', sa.String(length=40), nullable=True),
    sa.Column('education_label', sa.String(length=200), nullable=True),
    sa.Column('education_classification', sa.String(length=40), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('age_group', sa.String(length=40), nullable=True),
    sa.Column('rural_urban', sa.String(length=10), nullable=True),
    sa.Column('citizenship', sa.String(length=40), nullable=True),
    sa.Column('migrant_status', sa.String(length=40), nullable=True),
    sa.Column('formal_informal', sa.String(length=10), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('full_part_time', sa.String(length=10), nullable=True),
    sa.Column('source_population', sa.Text(), nullable=False),
    sa.Column('survey_name', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['external_observation_id'], ['external_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wage_observations_country'), 'wage_observations', ['country'], unique=False)
    op.create_index(op.f('ix_wage_observations_external_observation_id'), 'wage_observations', ['external_observation_id'], unique=False)
    op.create_index(op.f('ix_wage_observations_provider'), 'wage_observations', ['provider'], unique=False)
    op.create_index(op.f('ix_wage_observations_year'), 'wage_observations', ['year'], unique=False)

    # Phase 3 snapshots become finalized legacy snapshots; their pinned values move to snapshot_observations.
    import json
    rows = bind.execute(sa.text("SELECT id, items, created_at FROM episode_dataset_snapshots")).fetchall()
    for sid, items, created in rows:
        for it in (json.loads(items) if isinstance(items, str) else items) or []:
            bind.execute(sa.text("INSERT OR IGNORE INTO snapshot_observations (snapshot_id, external_observation_id, value, retrieved_at, payload) VALUES (:s,:o,:v,:r,:p)"),
                         {"s": sid, "o": it["observationId"], "v": it["value"], "r": it.get("retrievedAt", ""), "p": json.dumps(it)})
        bind.execute(sa.text("UPDATE episode_dataset_snapshots SET status='final', finalized_at=:c, notes='Phase 3 snapshot (legacy, unhashed)' WHERE id=:s"), {"s": sid, "c": created})

    # Immutability is enforced by the database itself, not only by the API.
    for t in ("snapshot_facts", "snapshot_observations", "snapshot_baselines"):
        for ev, ref in (("UPDATE", "OLD"), ("DELETE", "OLD"), ("INSERT", "NEW")):
            op.execute(f"""CREATE TRIGGER {t}_final_{ev.lower()} BEFORE {ev} ON {t}
                WHEN (SELECT status FROM episode_dataset_snapshots WHERE id = {ref}.snapshot_id) = 'final'
                BEGIN SELECT RAISE(ABORT, 'dataset snapshot is finalized and immutable'); END;""")
    op.execute("""CREATE TRIGGER snapshot_final_update BEFORE UPDATE ON episode_dataset_snapshots
        WHEN OLD.status = 'final' BEGIN SELECT RAISE(ABORT, 'dataset snapshot is finalized and immutable'); END;""")
    op.execute("""CREATE TRIGGER snapshot_final_delete BEFORE DELETE ON episode_dataset_snapshots
        WHEN OLD.status = 'final' AND (SELECT COUNT(*) FROM episodes WHERE id = OLD.episode_id) > 0
        BEGIN SELECT RAISE(ABORT, 'dataset snapshot is finalized and immutable'); END;""")
    # ### end Alembic commands ###


def downgrade():
    for t in ("snapshot_facts", "snapshot_observations", "snapshot_baselines"):
        for ev in ("update", "delete", "insert"):
            op.execute(f"DROP TRIGGER IF EXISTS {t}_final_{ev}")
    op.execute("DROP TRIGGER IF EXISTS snapshot_final_update")
    op.execute("DROP TRIGGER IF EXISTS snapshot_final_delete")
    for t in ("snapshot_observations", "snapshot_facts", "snapshot_baselines", "income_streams", "economic_baselines", "candidate_reviews",
              "wage_distribution_bins", "household_units", "evidence_gaps", "character_economic_profiles", "wage_distributions", "wage_observations"):
        op.drop_table(t)
    with op.batch_alter_table('episode_dataset_snapshots', schema=None) as batch_op:
        for c in ("content_hash", "finalized_at", "parent_id", "version", "notes", "status"):
            batch_op.drop_column(c)
