"""life context evidence

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 21:47:40.267440
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_evidence',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('population_scope', sa.Text(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_evidence_country'), ['country'], unique=False)

    op.create_table('historical_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('geography', sa.JSON(), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('economic_relevance', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('verification', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_evidence',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('policy_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('effective_start', sa.String(length=10), nullable=False),
    sa.Column('effective_end', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_organization', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fact_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('verification', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_evidence_country'), ['country'], unique=False)

    op.create_table('assumptions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('life_stage', sa.String(length=40), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('supporting_evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assumptions_episode_id'), ['episode_id'], unique=False)

    op.create_table('life_observations',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('external_observation_id', sa.String(length=160), nullable=True),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('metric_label', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('geo_level', sa.String(length=12), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('age_group', sa.String(length=40), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('education_level', sa.String(length=60), nullable=True),
    sa.Column('urban_rural', sa.String(length=10), nullable=True),
    sa.Column('income_group', sa.String(length=60), nullable=True),
    sa.Column('household_type', sa.String(length=80), nullable=True),
    sa.Column('housing_type', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('origin_country', sa.String(length=8), nullable=True),
    sa.Column('destination_country', sa.String(length=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('population_scope', sa.Text(), nullable=False),
    sa.Column('observation_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('dataset', sa.String(length=200), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_organization', sa.Text(), nullable=False),
    sa.Column('is_prototype', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['external_observation_id'], ['external_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('life_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_observations_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_observations_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_observations_external_observation_id'), ['external_observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_observations_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_observations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_observations_year'), ['year'], unique=False)

    op.create_table('life_stage_baselines',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('life_stage', sa.String(length=40), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('estimate_kind', sa.String(length=12), nullable=False),
    sa.Column('low', sa.String(length=60), nullable=True),
    sa.Column('high', sa.String(length=60), nullable=True),
    sa.Column('point', sa.String(length=60), nullable=True),
    sa.Column('distribution', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('coverage_type', sa.String(length=10), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('assumption_ids', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('user_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('life_stage_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_stage_baselines_episode_id'), ['episode_id'], unique=False)

    op.create_table('migration_paths',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=8), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_paths_episode_id'), ['episode_id'], unique=False)

    op.create_table('snapshot_records',
    sa.Column('snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('record_id', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['episode_dataset_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'record_type', 'record_id')
    )
    with op.batch_alter_table('evidence_gaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('life_stage', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('target_population', sa.Text(), nullable=True))

    # ### end Alembic commands ###

    # Immutability of Phase 5 snapshot contents is enforced by the database, like Phase 4 tables.
    for ev, ref in (("UPDATE", "OLD"), ("DELETE", "OLD"), ("INSERT", "NEW")):
        op.execute(f"""CREATE TRIGGER snapshot_records_final_{ev.lower()} BEFORE {ev} ON snapshot_records
            WHEN (SELECT status FROM episode_dataset_snapshots WHERE id = {ref}.snapshot_id) = 'final'
            BEGIN SELECT RAISE(ABORT, 'dataset snapshot is finalized and immutable'); END;""")


def downgrade():
    for ev in ("update", "delete", "insert"):
        op.execute(f"DROP TRIGGER IF EXISTS snapshot_records_final_{ev}")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_gaps', schema=None) as batch_op:
        batch_op.drop_column('target_population')
        batch_op.drop_column('life_stage')
        batch_op.drop_column('domain')

    op.drop_table('snapshot_records')
    with op.batch_alter_table('migration_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_paths_episode_id'))

    op.drop_table('migration_paths')
    with op.batch_alter_table('life_stage_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_stage_baselines_episode_id'))

    op.drop_table('life_stage_baselines')
    with op.batch_alter_table('life_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_observations_year'))
        batch_op.drop_index(batch_op.f('ix_life_observations_provider'))
        batch_op.drop_index(batch_op.f('ix_life_observations_metric'))
        batch_op.drop_index(batch_op.f('ix_life_observations_external_observation_id'))
        batch_op.drop_index(batch_op.f('ix_life_observations_domain'))
        batch_op.drop_index(batch_op.f('ix_life_observations_country'))

    op.drop_table('life_observations')
    with op.batch_alter_table('assumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assumptions_episode_id'))

    op.drop_table('assumptions')
    with op.batch_alter_table('policy_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_evidence_country'))

    op.drop_table('policy_evidence')
    op.drop_table('historical_events')
    with op.batch_alter_table('context_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_evidence_country'))

    op.drop_table('context_evidence')
    # ### end Alembic commands ###
