"""simulation engine

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 22:24:32.393450
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(length=80), nullable=True),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_priors',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parameter', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_priors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_priors_key'), ['key'], unique=False)

    op.create_table('candidate_evidence',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=True),
    sa.Column('research_task_id', sa.String(length=80), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('period_start', sa.Integer(), nullable=True),
    sa.Column('period_end', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('proposed_type', sa.String(length=30), nullable=False),
    sa.Column('submitted_by', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_evidence_episode_id'), ['episode_id'], unique=False)

    op.create_table('simulation_inputs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('dataset_snapshot_id', sa.String(length=80), nullable=False),
    sa.Column('character_version', sa.String(length=64), nullable=False),
    sa.Column('assumption_ids', sa.JSON(), nullable=False),
    sa.Column('locked_timeline_event_ids', sa.JSON(), nullable=False),
    sa.Column('prior_ids', sa.JSON(), nullable=False),
    sa.Column('prior_registry_version', sa.String(length=64), nullable=False),
    sa.Column('economic_engine_version', sa.String(length=20), nullable=False),
    sa.Column('simulation_engine_version', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('master_seed', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('review', sa.JSON(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_inputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_inputs_episode_id'), ['episode_id'], unique=False)

    op.create_table('simulation_jobs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=True),
    sa.Column('completed_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_jobs_episode_id'), ['episode_id'], unique=False)

    op.create_table('story_artifacts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_artifacts_episode_id'), ['episode_id'], unique=False)

    op.create_table('life_simulation_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.String(length=80), nullable=False),
    sa.Column('input_id', sa.String(length=80), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('batch_id', sa.String(length=80), nullable=True),
    sa.Column('parent_run_id', sa.String(length=80), nullable=True),
    sa.Column('branch_year', sa.Integer(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('final_state', sa.JSON(), nullable=False),
    sa.Column('economic_summary', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('quality_report', sa.JSON(), nullable=False),
    sa.Column('audit', sa.JSON(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('canonical_at', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('completed_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['input_id'], ['simulation_inputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('life_simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_simulation_runs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_simulation_runs_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_simulation_runs_input_id'), ['input_id'], unique=False)

    op.create_table('annual_life_states',
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('employment_state', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('income', sa.String(length=40), nullable=False),
    sa.Column('net_worth', sa.String(length=40), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['life_simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'year')
    )
    op.create_table('simulation_events',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('state_before', sa.JSON(), nullable=False),
    sa.Column('state_after', sa.JSON(), nullable=False),
    sa.Column('probability', sa.String(length=20), nullable=True),
    sa.Column('probability_class', sa.String(length=30), nullable=False),
    sa.Column('probability_source_ids', sa.JSON(), nullable=False),
    sa.Column('fact_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('assumption_ids', sa.JSON(), nullable=False),
    sa.Column('prior_ids', sa.JSON(), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_version', sa.String(length=10), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=False),
    sa.Column('base_probability', sa.String(length=20), nullable=True),
    sa.Column('random_draw', sa.String(length=20), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('occurred', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['life_simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_events_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simulation_run_id', sa.String(length=80), nullable=True))

    # A SimulationInput is frozen the moment it is created.
    op.execute("""CREATE TRIGGER simulation_inputs_immutable BEFORE UPDATE ON simulation_inputs
        BEGIN SELECT RAISE(ABORT, 'simulation input is frozen and immutable'); END;""")

    # ### end Alembic commands ###


def downgrade():
    op.execute('DROP TRIGGER IF EXISTS simulation_inputs_immutable')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_column('simulation_run_id')

    with op.batch_alter_table('simulation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_events_run_id'))

    op.drop_table('simulation_events')
    op.drop_table('annual_life_states')
    with op.batch_alter_table('life_simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_simulation_runs_input_id'))
        batch_op.drop_index(batch_op.f('ix_life_simulation_runs_episode_id'))
        batch_op.drop_index(batch_op.f('ix_life_simulation_runs_batch_id'))

    op.drop_table('life_simulation_runs')
    with op.batch_alter_table('story_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_artifacts_episode_id'))

    op.drop_table('story_artifacts')
    with op.batch_alter_table('simulation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_jobs_episode_id'))

    op.drop_table('simulation_jobs')
    with op.batch_alter_table('simulation_inputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_inputs_episode_id'))

    op.drop_table('simulation_inputs')
    with op.batch_alter_table('candidate_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_evidence_episode_id'))

    op.drop_table('candidate_evidence')
    with op.batch_alter_table('simulation_priors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_priors_key'))

    op.drop_table('simulation_priors')
    op.drop_table('agent_jobs')
    # ### end Alembic commands ###
