/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as DataRouteImport } from './routes/data'
import { Route as DnaRouteImport } from './routes/dna'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as LaborRouteImport } from './routes/labor'
import { Route as LifeDataRouteImport } from './routes/life-data'
import { Route as LifeEvidenceRouteImport } from './routes/life-evidence'
import { Route as ModelValidationRouteImport } from './routes/model-validation'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as StatusRouteImport } from './routes/status'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as EpisodesIndexRouteImport } from './routes/episodes.index'
import { Route as EpisodesNewRouteImport } from './routes/episodes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaRoute = DnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborRoute = LaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeDataRoute = LifeDataRouteImport.update({
  id: '/life-data',
  path: '/life-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeEvidenceRoute = LifeEvidenceRouteImport.update({
  id: '/life-evidence',
  path: '/life-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelValidationRoute = ModelValidationRouteImport.update({
  id: '/model-validation',
  path: '/model-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesIndexRoute = EpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesNewRoute = EpisodesNewRouteImport.update({
  id: '/episodes/new',
  path: '/episodes/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/data': typeof DataRoute
  '/dna': typeof DnaRoute
  '/economics': typeof EconomicsRoute
  '/evidence': typeof EvidenceRoute
  '/facts': typeof FactsRoute
  '/labor': typeof LaborRoute
  '/life-data': typeof LifeDataRoute
  '/life-evidence': typeof LifeEvidenceRoute
  '/model-validation': typeof ModelValidationRoute
  '/production': typeof ProductionRoute
  '/receipt': typeof ReceiptRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/snapshots': typeof SnapshotsRoute
  '/sources': typeof SourcesRoute
  '/status': typeof StatusRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/episodes/new': typeof EpisodesNewRoute
  '/episodes/': typeof EpisodesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/data': typeof DataRoute
  '/dna': typeof DnaRoute
  '/economics': typeof EconomicsRoute
  '/evidence': typeof EvidenceRoute
  '/facts': typeof FactsRoute
  '/labor': typeof LaborRoute
  '/life-data': typeof LifeDataRoute
  '/life-evidence': typeof LifeEvidenceRoute
  '/model-validation': typeof ModelValidationRoute
  '/production': typeof ProductionRoute
  '/receipt': typeof ReceiptRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/snapshots': typeof SnapshotsRoute
  '/sources': typeof SourcesRoute
  '/status': typeof StatusRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/episodes/new': typeof EpisodesNewRoute
  '/episodes': typeof EpisodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/data': typeof DataRoute
  '/dna': typeof DnaRoute
  '/economics': typeof EconomicsRoute
  '/evidence': typeof EvidenceRoute
  '/facts': typeof FactsRoute
  '/labor': typeof LaborRoute
  '/life-data': typeof LifeDataRoute
  '/life-evidence': typeof LifeEvidenceRoute
  '/model-validation': typeof ModelValidationRoute
  '/production': typeof ProductionRoute
  '/receipt': typeof ReceiptRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/snapshots': typeof SnapshotsRoute
  '/sources': typeof SourcesRoute
  '/status': typeof StatusRoute
  '/story': typeof StoryRoute
  '/timeline': typeof TimelineRoute
  '/episodes/new': typeof EpisodesNewRoute
  '/episodes/': typeof EpisodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audits'
    | '/data'
    | '/dna'
    | '/economics'
    | '/evidence'
    | '/facts'
    | '/labor'
    | '/life-data'
    | '/life-evidence'
    | '/model-validation'
    | '/production'
    | '/receipt'
    | '/research'
    | '/settings'
    | '/simulation'
    | '/snapshots'
    | '/sources'
    | '/status'
    | '/story'
    | '/timeline'
    | '/episodes/new'
    | '/episodes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audits'
    | '/data'
    | '/dna'
    | '/economics'
    | '/evidence'
    | '/facts'
    | '/labor'
    | '/life-data'
    | '/life-evidence'
    | '/model-validation'
    | '/production'
    | '/receipt'
    | '/research'
    | '/settings'
    | '/simulation'
    | '/snapshots'
    | '/sources'
    | '/status'
    | '/story'
    | '/timeline'
    | '/episodes/new'
    | '/episodes'
  id:
    | '__root__'
    | '/'
    | '/audits'
    | '/data'
    | '/dna'
    | '/economics'
    | '/evidence'
    | '/facts'
    | '/labor'
    | '/life-data'
    | '/life-evidence'
    | '/model-validation'
    | '/production'
    | '/receipt'
    | '/research'
    | '/settings'
    | '/simulation'
    | '/snapshots'
    | '/sources'
    | '/status'
    | '/story'
    | '/timeline'
    | '/episodes/new'
    | '/episodes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditsRoute: typeof AuditsRoute
  DataRoute: typeof DataRoute
  DnaRoute: typeof DnaRoute
  EconomicsRoute: typeof EconomicsRoute
  EvidenceRoute: typeof EvidenceRoute
  FactsRoute: typeof FactsRoute
  LaborRoute: typeof LaborRoute
  LifeDataRoute: typeof LifeDataRoute
  LifeEvidenceRoute: typeof LifeEvidenceRoute
  ModelValidationRoute: typeof ModelValidationRoute
  ProductionRoute: typeof ProductionRoute
  ReceiptRoute: typeof ReceiptRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  SimulationRoute: typeof SimulationRoute
  SnapshotsRoute: typeof SnapshotsRoute
  SourcesRoute: typeof SourcesRoute
  StatusRoute: typeof StatusRoute
  StoryRoute: typeof StoryRoute
  TimelineRoute: typeof TimelineRoute
  EpisodesNewRoute: typeof EpisodesNewRoute
  EpisodesIndexRoute: typeof EpisodesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna': {
      id: '/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof DnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor': {
      id: '/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof LaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-data': {
      id: '/life-data'
      path: '/life-data'
      fullPath: '/life-data'
      preLoaderRoute: typeof LifeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-evidence': {
      id: '/life-evidence'
      path: '/life-evidence'
      fullPath: '/life-evidence'
      preLoaderRoute: typeof LifeEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-validation': {
      id: '/model-validation'
      path: '/model-validation'
      fullPath: '/model-validation'
      preLoaderRoute: typeof ModelValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/': {
      id: '/episodes/'
      path: '/episodes'
      fullPath: '/episodes/'
      preLoaderRoute: typeof EpisodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/new': {
      id: '/episodes/new'
      path: '/episodes/new'
      fullPath: '/episodes/new'
      preLoaderRoute: typeof EpisodesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditsRoute: AuditsRoute,
  DataRoute: DataRoute,
  DnaRoute: DnaRoute,
  EconomicsRoute: EconomicsRoute,
  EvidenceRoute: EvidenceRoute,
  FactsRoute: FactsRoute,
  LaborRoute: LaborRoute,
  LifeDataRoute: LifeDataRoute,
  LifeEvidenceRoute: LifeEvidenceRoute,
  ModelValidationRoute: ModelValidationRoute,
  ProductionRoute: ProductionRoute,
  ReceiptRoute: ReceiptRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  SimulationRoute: SimulationRoute,
  SnapshotsRoute: SnapshotsRoute,
  SourcesRoute: SourcesRoute,
  StatusRoute: StatusRoute,
  StoryRoute: StoryRoute,
  TimelineRoute: TimelineRoute,
  EpisodesNewRoute: EpisodesNewRoute,
  EpisodesIndexRoute: EpisodesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
